knygmainys_books_homepage:
    path:     /
    defaults: { _controller: KnygmainysBooksBundle:Book:index }

knygmainys_books_create:
    path:     /prideti
    defaults: { _controller: KnygmainysBooksBundle:Book:create }

knygmainys_books_show:
    path:     /rodyti/{id}
    defaults: { _controller: KnygmainysBooksBundle:Book:show }
    methods: [GET]
    requirements:
        id: \d+

knygmainys_books_search_book_title:
    path:     /ieskoti-knygos
    defaults: { _controller: KnygmainysBooksBundle:Book:searchBookByTitle }

knygmainys_books_search_book_author:
    path:     /ieskoti-autoriaus
    defaults: { _controller: KnygmainysBooksBundle:Book:searchAuthor }