knygmainys_books_homepage:
    path:     /{page}
    defaults: { _controller: KnygmainysBooksBundle:Book:index, page: 1 }
    methods: [GET]
    requirements:
        page: \d+

knygmainys_books_create:
    path:     /prideti
    defaults: { _controller: KnygmainysBooksBundle:Book:create }

knygmainys_books_show:
    path:     /rodyti/{id}
    defaults: { _controller: KnygmainysBooksBundle:Book:show }
    methods: [GET]
    requirements:
        id: \d+

knygmainys_books_show_wanted:
    path:     /norimos
    defaults: { _controller: KnygmainysBooksBundle:Book:wanted }

knygmainys_books_show_owned:
    path:     /turimos
    defaults: { _controller: KnygmainysBooksBundle:Book:owned }

knygmainys_books_show_contributed:
    path:     /atiduotos
    defaults: { _controller: KnygmainysBooksBundle:Book:contributed }

knygmainys_books_show_received:
    path:     /gautos
    defaults: { _controller: KnygmainysBooksBundle:Book:received }

knygmainys_books_request:
    path:     /prasymas/{id}
    defaults: { _controller: KnygmainysBooksBundle:Book:request }
    methods: [GET]
    requirements:
        id: \d+

knygmainys_books_request_status:
    path:     /prasymo-statusas
    defaults: { _controller: KnygmainysBooksBundle:Book:requestStatus }

knygmainys_books_offer:
    path:     /pasiulymas/{id}
    defaults: { _controller: KnygmainysBooksBundle:Book:offer }
    methods: [GET]
    requirements:
        id: \d+

knygmainys_books_offer_status:
    path:     /pasiulymo-statusas
    defaults: { _controller: KnygmainysBooksBundle:Book:offerStatus }

knygmainys_books_release_create:
    path:     /leidimas/prideti
    defaults: { _controller: KnygmainysBooksBundle:Release:create }

knygmainys_books_search_book_title:
    path:     /ieskoti-knygos
    defaults: { _controller: KnygmainysBooksBundle:Book:searchBookByTitle }

knygmainys_books_search_book_author:
    path:     /ieskoti-autoriaus
    defaults: { _controller: KnygmainysBooksBundle:Book:searchAuthor }

knygmainys_books_search_release_isbn:
    path:     /ieskoti-isbn/{book}
    defaults: { _controller: KnygmainysBooksBundle:Release:searchISBN }
    requirements:
        id: \d+

knygmainys_books_book_transfer:
    path:     /klausti-vartotojo
    defaults: { _controller: KnygmainysBooksBundle:Book:addBookToUser }

knygmainys_books_add_book:
    path:     /prideti-knyga
    defaults: { _controller: KnygmainysBooksBundle:Book:addBookToList }