knygmainys_books_homepage:
    path:     /{page}
    defaults: { _controller: KnygmainysBooksBundle:Book:index, page: 1 }
    methods: [GET]
    requirements:
        page: \d+

knygmainys_books_create:
    path:     /prideti
    defaults: { _controller: KnygmainysBooksBundle:Book:create }

knygmainys_books_show:
    path:     /rodyti/{id}
    defaults: { _controller: KnygmainysBooksBundle:Book:show }
    methods: [GET]
    requirements:
        id: \d+

knygmainys_books_release_create:
    path:     /leidimas/prideti
    defaults: { _controller: KnygmainysBooksBundle:Release:create }

knygmainys_books_search_book_title:
    path:     /ieskoti-knygos
    defaults: { _controller: KnygmainysBooksBundle:Book:searchBookByTitle }

knygmainys_books_search_book_author:
    path:     /ieskoti-autoriaus
    defaults: { _controller: KnygmainysBooksBundle:Book:searchAuthor }

knygmainys_books_search_release_isbn:
    path:     /ieskoti-isbn/{book}
    defaults: { _controller: KnygmainysBooksBundle:Release:searchISBN }
    requirements:
        id: \d+

knygmainys_books_add_book:
    path:     /prideti-knyga
    defaults: { _controller: KnygmainysBooksBundle:Book:addBookToList }