services:
#    knygmainys_user.example:
#        class: Knygmainys\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%
    knygmainys_user.registration.form.type:
        class: Knygmainys\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: knygmainys_user_registration }