homepage:
    pattern:   /
    defaults:  { _controller: KnygmainysMainBundle:Main:index }

knygmainys_admin:
    resource: "@KnygmainysAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

knygmainys_main:
    resource: "@KnygmainysMainBundle/Resources/config/routing.yml"
    prefix:   /

knygmainys_books:
    resource: "@KnygmainysBooksBundle/Resources/config/routing.yml"
    prefix:   /knygos

knygmainys_user:
    resource: "@KnygmainysUserBundle/Resources/config/routing.yml"
    prefix:   /vartotojas

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"